FORMAT: 1A
HOST: http://localhost:8000/api

# CMS

CMS is a simple API allowing consumers to view complaints and register complaints in them.

## get system issue status [/master/issue-status]

### get issue status [GET]
+ Response 200 (application/json)

        {
         
          "data": [
            {
              "system_complaints_status_id": 1,
              "name": "Open",
              "created_at": 2016-03-15 12:24:15,
              "updated_at": 2016-03-15 12:24:15
            },
            {
              "system_complaints_status_id": 2,
              "name": "Closed",
              "created_at": 2016-03-15 12:24:15,
              "updated_at": 2016-03-15 12:24:15
            }
          ],
           "code": 200,
        }



## get issue types [/master/issue-types]

### get issue types [GET]
+ Response 200 (application/json)

        {
         
          "data": [
            {
              "system_issue_type_id": 1,
              "name": "battery",
              "created_at": 2016-03-15 12:24:15,
              "updated_at": 2016-03-15 12:24:15
            },
            {
              "system_issue_type_id": 2,
              "name": "dull display",
              "created_at": 2016-03-15 12:24:15,
              "updated_at": 2016-03-15 12:24:15
            }
          ],
           "code": 200,
        }
 
## get system status [/master/system-status]

### get system status [GET]
+ Response 200 (application/json)

        {
         
          "data": [
            {
              "system_status_id": 1,
              "name": "up",
              "created_at": 2016-03-15 12:24:15,
              "updated_at": 2016-03-15 12:24:15
            },
            {
              "system_status_id": 2,
              "name": "down",
              "created_at": 2016-03-15 12:24:15,
              "updated_at": 2016-03-15 12:24:15
            }
          ],
           "code": 200,
        }

## get system details [/master/system-detail]

### get system details [GET]
+ Response 200 (application/json)

        {
         
          "data": [
            {
              "system_detail_id": 1,
              "name": "warranty",
              "created_at": 2016-03-15 12:24:15,
              "updated_at": 2016-03-15 12:24:15
            },
            {
              "system_detail_id": 2,
              "name": "call basic",
              "created_at": 2016-03-15 12:24:15,
              "updated_at": 2016-03-15 12:24:15
            }
          ],
           "code": 200,
        }

## get system config [/master/system-config]

### get system config [GET]
+ Response 200 (application/json)

        {
         
          "data": [
            {
              "system_config_id": 1,
              "name": "laptot",
              "created_at": 2016-03-15 12:24:15,
              "updated_at": 2016-03-15 12:24:15
            },
            {
              "system_config_id": 2,
              "name": "desktop",
              "created_at": 2016-03-15 12:24:15,
              "updated_at": 2016-03-15 12:24:15
            }
          ],
           "code": 200,
        }
        
## get system model [/master/system-model]

### get system model [GET]
+ Response 200 (application/json)

        {
         
          "data": [
            {
              "model_id": 1,
              "name": "leneovo c-30-40",
              "created_at": 2016-03-15 12:24:15,
              "updated_at": 2016-03-15 12:24:15
            },
            {
              "model_id": 2,
              "name": "leneovo c-31-45",
              "created_at": 2016-03-15 12:24:15,
              "updated_at": 2016-03-15 12:24:15
            }
          ],
           "code": 200,
        }
    
## get user profile details [/user/user-profile]

### get user profile [GET]
+ Response 200 (application/json)

         
            "data": [
            {
              "user_id": 1,
              "name": "leneovo c-30-40",
              "company": "ABC Corp",
              "address_1": "ABC DOM",
              "mobile_no": "8766509932"
              "landline_no": 0234-10022222,
              "is_login"   :1
              "created_at": 2016-03-15 12:24:15,
              "updated_at": 2016-03-15 12:24:15
            }
             
          ],
           "code": 200,
        }

## user register complaint  [/user/complaint/]

### user register complaint [POST]

+ Request (application/json)

        {
            
              "system_issue_type_id":               1,
              "system_complaints_status_id":        1,
              "complaint-description":           "blue screen,dull display",
             
        }

+ Response 200 (application/json)

        {
          "data": {
           
            "user" :{
            "name": "Viraj",
            "email": "viraj@gmail.com",
            "contact": "9819213531",
            "address":"Abc Dom(E)",
            "auth-token":"12awrqrrqrrr",
             "system_issue_type_id":               1,
            "system_complaints_status_id":        1,
            "name":                            "open"
            "complaint-description":            "blue screen,dull display",
             "date": 2016-4-4,
             "time":3:30
         
          },
          "message": "complaint register successfully.",
          "code": 201
        }
        

## list a complaints [/user/complain-list]

### list a complaints [GET]
+ Response 200 (application/json)

         
            "data": [
                {
                    "complaints_details_id":1,
                    "system_issue_type_id":               1,
                    "name":"dull display",
                    "system_complaints_status_id":        1,
                    "name":"open"
                    "complaint-description":           "blue screen,dull display",
                {
                
                    "complaints_details_id":2,
                    "system_issue_type_id":               1,
                    "name":"dull display",
                    "system_complaints_status_id":        1,
                    "name":"open"
                    "complaint-description":           "blue screen,dull display",
                
                
                }
              
             
          ], 
                  "paginator": {
                    "total_count": 2,
                    "total_pages": 1,
                    "current_page": 1,
                    "limit": 10,
                    "next_page_url": null,
                    "previous_page_url": null
                  },
                  "code": 200
        }

## view complain detials  [/user/complain/{complaint_details_id}]
+ Parameters
    +      complaint_details_id (number) - ID of the  complaint_details  in the form of an integer

### view complain detials  [GET]

+ Response 200 (application/json)

        {
          "data": [
            {
             
              "complain": {
                    "complaints_details_id":1,
                    "system_issue_type_id":               1,
                    "name":"dull display",
                    "system_complaints_status_id":        1,
                    "name":"open"
                    "complaint-description":           "blue screen,dull display",
          
              },
            }
          ],
          "paginator": {
            "total_count": 2,
            "total_pages": 1,
            "current_page": 1,
            "limit": 10,
            "next_page_url": null,
            "previous_page_url": null
          },
          "code": 200
        }